### ISSUE TITLE
lisk psql binaries link against readline-6

### ISSUE THREAD

**Issue by 4fryn** [4fryn/lisk-archlinux#1]
psql: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

**Comment by 4fryn** [comment]
tracking upstream at https://github.com/LiskHQ/lisk-build/issues/132

**Comment by Isabello** [comment]
related: https://github.com/LiskHQ/lisk-build/issues/133

**Comment by 4fryn** [comment]
works fine with readline 7, fixed in #3
